### ISSUE TITLE
Nested selector classes

### ISSUE THREAD

**Issue by tomahl** [mayank99/ecsstatic#9] opened 2023-02-14 09:39 UTC
Hi again,

When using nested selectors with the `scss` function like below:

```tsx
const fooBar = scss`
    color: red;

    &_mod {
        color: green
    }
`
```

There is no type-safe way of using the **nested** generated className. The className also appears to be only partially scoped/hashed e.g. `.🎈-1ayuydh_red` instead of `.🎈-1ayuydhxxx`.

If you write the same thing with the `css` function, an invalid selector is created `_red.🎈-1ayuydh`, but on the other hand, it was perhaps never meant to work. It would have been nice if the Sass-based example would work though. :)

Thanks

**Comment by mayank99** [comment] 2023-02-14 14:08
Can I ask about your use case? Selector concatenation kinda doesn't make sense for ecsstatic because the actual class is an implementation detail.

**Comment by tomahl** [comment] 2023-02-14 14:26
I'm looping an array to create modifier-selectors but maybe it should be done differently within ecsstatic?

```tsx
const avatar = css`
	/* ... */
	background-color: var(--avatar-color, var(${vars.colors.grey400}));
        /* ... */
	
        ${COLORS.map(
		(color) => `
			&_${color} {
				--avatar-color: var(${vars.colors[color]});
			}
		`
	).join()}
`;
```

**Comment by mayank99** [comment] 2023-02-14 15:28
You could try using data attributes (or even unscoped classes). This pattern is quite useful and I use it all the time.
```jsx
const avatar = css`
	${COLORS.map(
		(color) => `
			&[data-color=${color}] {
				--avatar-color: var(${vars.colors[color]});
			}
		`
	).join()}
`;
```

Alternatively, you could generate classes separately instead of nesting. I *think* this should work but I have not tested it.
```jsx
const avatarColors = COLORS.map((color) => 
	[color]: css`--avatar-color: var(${vars.colors[color]});`
);
```

**Comment by tomahl** [comment] 2023-02-14 15:44
I actually went for the data-attr solution before you wrote but I'm gonna try the second approach as well. Thanks for the suggestion. 👍 

What I'm trying to do all-in-all is creating all my apps css with TS, all the way, even the `--css-vars`. Now I'm stuck with the global styles. Do you have any creative solution for that as well? I don't want to use vanilla CSS for the main stylesheet and loose access to TS.

**Comment by mayank99** [comment] 2023-02-14 16:35
Depending on your build setup, you might be able to export CSS variables into JS or write a script to generate the global stylesheet from a JSON file. And you then could write a function that resolves to the correct CSS variable name and generate correct typings for it.
```ts
// use `globalVars` in your script to generate your global stylesheet
export const globalVars = {
  'background-main': 'hotpink',
  'text-main': 'black',
  // ...
};

// use `token` inside component css
export function token(val: keyof typeof globalVars, fallback: string) {
  return `var(--${val}, ${fallback})`
}
```

From the perspective of ecsstatic, all that's really needed is JavaScript variables that you can interpolate inside `css`.
```js
css`background-color: ${tokens('backgroundMain')}`
```

However, I should warn that the goal of ecsstatic is pretty narrow: solve scoped classes and colocation without impacting runtime performance (you can read more [here](https://blog.mayank.co/is-css-in-js-actually-bad)). The more fancy stuff you try to do, the more work it will be for you and the more problems you'll run into.

For fully typed CSS, vanilla-extract is probably a better fit.

**Comment by mayank99** [comment] 2023-02-15 00:28
Since there is no real bug here, I will close this as "working as intended".

**Closed by mayank99** 2023-02-15 00:28 UTC
