### ISSUE TITLE
Styles not being extracted, but class is present in SolidJS render

### ISSUE THREAD

**Issue by ivancuric** [mayank99/ecsstatic#17] opened 2023-07-18 10:32 UTC
Not something I was able to reproduce on a smaller sample, but at one point some components simply stopped having their styles generated. I will have a hash, like `ez5lpn`, but the generated CSS is empty.

Extracting to smaller components doesn't help.

I'm using SolidJS. Is there anything I can do to give you more context, as I am currently unable to share the project itself?

What I've noticed is that ordering seems to matter. If I move one component lower in the tree or higher, this will have an impact on which components will stop having their styles generated.

Extracting the css from an inline `class={css``}` to a declaration outside the component helps.

**Comment by mayank99** [comment] 2023-07-18 13:04
could you share your component file and your config if possible?

and yes, ` css`` ` is mainly meant to be assigned to declarations, especially when interpolating values.

**Comment by ivancuric** [comment] 2023-07-18 13:06
Will try to make a repro!

Having inline `css`` ` was actually the main selling point as I was looking for a Tailwind alternative.

**Comment by mayank99** [comment] 2023-07-18 18:46
thanks for the info, i'll investigate this. the commented out code might be affecting output due to a string escaping issue.

**Comment by mayank99** [comment] 2023-07-18 18:47
as for the order thing, i would recommend using [cascade layers](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) if you have conflicting styles applied on the same element.

**Comment by mayank99** [comment] 2023-07-28 00:22
unfortunately, i have not been able to reproduce this.

the commented out code thing might just be an HMR issue. if you refresh the page, it *should* remove any styles for commented out code.

other than that, i would need more info to really be able to help you out.
- package versions

**Closed** 2024-02-04 01:07 UTC
